name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Release
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: "x86_64-apple-darwin"
            os: "macos-latest"
          - target: "aarch64-apple-darwin"
            os: "macos-latest"
          - target: "x86_64-unknown-linux-gnu"
            os: "ubuntu-latest"
          - target: "aarch64-unknown-linux-gnu"
            os: "ubuntu-latest"
          - target: "x86_64-pc-windows-msvc"
            os: "windows-latest"
          - target: "aarch64-pc-windows-msvc"
            os: "windows-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Build and deploy artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#*/tags/}
          mkdir dist
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]
          then
          7z a ../../../dist/wordle-${TAG}-${{ matrix.target }}.zip wordle.exe
          else
          tar czf ../../../dist/wordle-${TAG}-${{ matrix.target }}.tar.gz wordle
          fi
        shell: bash
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
